### ISSUE TITLE
openssl dhparam takes a lot of time on smaller machines(aws ec2 micro)

### ISSUE THREAD

**Issue by prasadpilla** [aleks/ansible-rails#14]
Hey @aleks, Thanks so much for building this. Made provision and initial setup super easy and repeatable. 

openssl dhparam -out /etc/nginx/dhparam.pem 4096 takes around 15 mins sometimes. Can we add -"dsaparam" as mentioned here https://security.stackexchange.com/questions/95178/diffie-hellman-parameters-still-calculating-after-24-hours

**Comment by aleks** [comment]
Hey @prasadpilla, thanks a lot!

I'm not sure how "equally secure" this really is. Do you have any other source (beside that stackexchange thread), which could provide more details on the security side of the change to `-dsaparam`?

To be honest, it's not "my fault" that AWS instances are so slow. And i don't want to sacrifice security for speed. But i'm open to change this setting, if it's really equally secure in every way. :)

**Comment by jrchamp** [comment]
From https://www.openssl.org/news/secadv/20160128.txt

"Non-safe primes are generated by OpenSSL when using ... dhparam with the -dsaparam option."

"[dsaparam] has always been documented as requiring the single use."

"OpenSSL provides the option SSL_OP_SINGLE_DH_USE for ephemeral DH (DHE) in TLS. It is not on by default. If the option is not set then the server reuses the same private DH exponent for the life of the server process and would be vulnerable to this attack."

**Comment by prasadpilla** [comment]
@jrchamp Thanks much for the clarification.
