### ISSUE TITLE
Failed to connect to the host via ssh: Permission denied (publickey,password)

### ISSUE THREAD

**Issue by gitleet** [aleks/ansible-rails#6]
Hi,

I'm confused as it initially connects using the root user, but where am I setting the root password?

I get this error:

`UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", "unreachable": true}`

**Comment by aleks** [comment]
You don't! This Playbook creates a deploy User and disables SSH access for the root user.

Here you can find the task: https://github.com/aleks/ansible-rails/blob/master/roles/deploy-user/tasks/main.yml
