### ISSUE TITLE
How to deploy without capistrano

### ISSUE THREAD

**Issue by gitleet** [aleks/ansible-rails#7]
Hello,
If I want to deploy without using capistrano, I can figure out out how to get the files on the server.

What path should I push the files too, do I have to do anything else other that push the files to the /current folder?

**Comment by gitleet** [comment]
Also, just to confirm:

deploy_server_hostname

The hostname should be the ip address correct?  Not the domain name?

Thanks!!

**Comment by aleks** [comment]
Hello,

no, `deploy_server_hostname` is the hostname, not the ip address. See: https://github.com/aleks/ansible-rails/search?utf8=%E2%9C%93&q=deploy_server_hostname

This Playbook is designed to work with capistrano. It's easier if you know how capistrano works. You're correct with your `/current` assumption, but please take a closer look, how capistrano structures your rails app: http://capistranorb.com/documentation/getting-started/structure/

**Comment by gitleet** [comment]
I just basically push to the /current folder and then I had to manually restart the puma/sidekiq process and it works.  I'm just using the sychronize command to take my local folder to remote.
thanks!
