### ISSUE TITLE
What os versions has this been tested on?

### ISSUE THREAD

**Issue by gitleet** [aleks/ansible-rails#8]
Just curious what os versions has this been tested on?

Does it only work with ubuntu or debian will also work?

**Comment by aleks** [comment]
I've run this playbook on ubuntu 16.04 and up. But if you're having issues with debian, feel free to report them.

**Comment by gitleet** [comment]
I was just trying to run this on debian 9 and ansible crashed on this line:

https://github.com/aleks/ansible-rails/blob/master/roles/mysql/tasks/main.yml#L8

The libmysqlclient-dev package doesn't exist on debian 9 for some reason.

**Comment by aleks** [comment]
I have not tested it with debian, you can try to fix this by just removing the package and see if it works. I have no debian system to test this myself.

I'm closing the issue, but if you find a workaround, feel free to write a comment.
